-- 코드를 입력하세요
/**
테이블 정보
1. TABLE 상반기 주문정보 : FIRST_HALF - SHIPMENT_ID, FLAVOR, TOTAL_ORDER
2. TABLE 성분정보 : ICECREAM_INFO - FLAVOR, INGREDITENT_TYPE

조건
1. TOTAL_ORDER > 3000
2. INGREDIENT_TYPE = fruit_based
3. TOTAL_ORDER DESC
**/
SELECT A.FLAVOR 
FROM FIRST_HALF AS A
   LEFT OUTER JOIN ICECREAM_INFO B
   ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER >= 3000
  AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC